# Generated by Django 4.1.2 on 2022-10-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                ("autor", models.CharField(max_length=30)),
                ("co_autor", models.CharField(blank=True, max_length=30)),
                ("editora", models.CharField(max_length=30)),
                ("data_cadastro", models.DateField()),
                ("emprestado", models.BooleanField(default=False)),
                ("nome_emprestado", models.CharField(blank=True, max_length=30)),
                ("data_emprestimo", models.DateTimeField(blank=True)),
                ("data_devolucao", models.DateField(blank=True)),
                ("tempo_duracao", models.DateField(blank=True)),
            ],
            options={"verbose_name": "Livro",},
        ),
    ]
