# Generated by Django 4.1.2 on 2022-10-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="data_cadastro",
            field=models.DateField(auto_now=True),
        ),
    ]
