# Generated by Django 4.1.2 on 2022-10-10 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0002_alter_livro_data_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="data_cadastro",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="livro",
            name="data_devolucao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="data_emprestimo",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="tempo_duracao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
