# Generated by Django 4.1.2 on 2022-11-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0003_alter_livro_data_cadastro_alter_livro_data_devolucao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("descricao", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "Categoria",},
        ),
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="livro.categoria",
            ),
            preserve_default=False,
        ),
    ]
